name: Build and Publish image to Docker Hub and deploy to Railway

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t capstoneprojectbedocker:latest -f Dockerfile .

      - name: Tag Docker image
        run: docker tag capstoneprojectbedocker:latest trungthong/capstonebe:latest
        
      - name: Push Docker image to Docker Hub
        run: docker push trungthong/capstonebe:latest
